version: '3'
services:
  tadbirinsuranceapi: 
   build: 
    context: . 
    dockerfile: Dockerfile
   container_name: tadbirinsuranceapi
   volumes:
      - ${LOCAL_DOCKER_VOLUMES}/tadbirinsuranceapi/app:/app
   ports:
    - "5000:5000"
   networks:
      - default
# -----------------------------
# nginx proxy manager
# -----------------------------
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${LOCAL_DOCKER_VOLUMES}/nginxproxymanager/data:/data
      - ${LOCAL_DOCKER_VOLUMES}/nginxproxymanager/etc/letsencrypt:/etc/letsencrypt
    networks:
      - default
  # -----------------------------
  # postgres database
  # -----------------------------
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - ${LOCAL_DOCKER_VOLUMES}/postgres${PGDATA}:${PGDATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - default
# -----------------------------
# networks
# -----------------------------
networks:
  default:
     name: tadbirinsurancenetwork